<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h3_Shipping details</name>
   <tag></tag>
   <elementGuidId>e481a86f-89a3-4e05-bbc7-ea84ba266c80</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='myAccountContainer']/div[3]/h3</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h3.blueLink.ng-scope</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;Shipping details&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>8c0afe89-b4a7-43fd-a96d-e72febbf635a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>blueLink ng-scope</value>
      <webElementGuid>ba15dcf5-f392-4798-9bfe-d2cc3fcebff9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>translate</name>
      <type>Main</type>
      <value>Shipping_Details</value>
      <webElementGuid>c16a6a14-210e-4477-8efb-d727a4f7eab6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Shipping details</value>
      <webElementGuid>d2771d7b-3e4a-4229-ae76-7ec917e0ce60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;myAccountContainer&quot;)/div[@class=&quot;cube&quot;]/h3[@class=&quot;blueLink ng-scope&quot;]</value>
      <webElementGuid>1ca6fb61-295e-43fd-9b91-4cde5f50e775</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='myAccountContainer']/div[3]/h3</value>
      <webElementGuid>9a4a76b9-d816-4dd6-91f2-1086541e70e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='aaaa'])[2]/following::h3[1]</value>
      <webElementGuid>030636bb-6cdb-4d7b-8f55-68c6becaabea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='United States'])[2]/following::h3[1]</value>
      <webElementGuid>d27cfce3-7c9c-4f18-8f93-7c492291ac16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sonya Kaput'])[3]/preceding::h3[1]</value>
      <webElementGuid>67547712-c64e-416c-89b9-20ef6ddffc05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='adsfghfj'])[3]/preceding::h3[1]</value>
      <webElementGuid>a9089a42-7a71-4d00-8e06-772e27855e2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/h3</value>
      <webElementGuid>ce59a5c4-5dd4-417f-bf89-2885ea84e4aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[(text() = 'Shipping details' or . = 'Shipping details')]</value>
      <webElementGuid>e2524f26-b954-4f78-88a4-97bcdc6804d4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
