<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Choose payment method below_safepay</name>
   <tag></tag>
   <elementGuidId>6c73df01-7051-4288-a37c-f6efbeb325dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='safepay']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;safepay&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[name=&quot;safepay&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>291a74c2-b63a-4a72-97f9-dcbe9f30ed32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>1a6c72d0-3e04-4ed9-b829-75d03f875b06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>safepay</value>
      <webElementGuid>b4bebf3f-ca32-4feb-884d-17388454ea6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-checked</name>
      <type>Main</type>
      <value>checkedRadio == 1</value>
      <webElementGuid>5cf2583f-454d-410b-af79-cf62d092bcfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;paymentMethod&quot;)/div[1]/div[@class=&quot;paymentMethods&quot;]/div[@class=&quot;imgRadioButton&quot;]/input[1]</value>
      <webElementGuid>d62a431d-5dc4-4b71-86ee-38fac4b81602</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='safepay']</value>
      <webElementGuid>d8275d00-bac2-43fc-9a1e-21b776a3a708</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='paymentMethod']/div/div/div/input</value>
      <webElementGuid>e5944896-74e1-4654-9aed-01adebf9f510</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/input</value>
      <webElementGuid>bbb99907-b4b5-496a-920a-cadcdd33cbf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'safepay']</value>
      <webElementGuid>f42a4fe7-e85a-4009-88f2-447a278f9585</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
