<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_hdfhagkerf</name>
   <tag></tag>
   <elementGuidId>e9e562df-bbe2-459d-b3cc-1dd078938fa2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='userDetails']/div[2]/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div:nth-of-type(2) > label.ng-binding</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#userDetails >> internal:text=&quot;hdfhagkerf&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>5ace2a5f-28c2-4594-9a33-aad44c629bfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-show</name>
      <type>Main</type>
      <value>user.address != ''</value>
      <webElementGuid>f0a8791b-81a7-43ae-9191-cc384fb16399</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding</value>
      <webElementGuid>2eb5c2f4-26d4-489a-ba69-1851ad4e5c80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>hdfhagkerf</value>
      <webElementGuid>e7ece9df-a538-4c74-a107-4d52e1c80808</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;userDetails&quot;)/div[2]/label[@class=&quot;ng-binding&quot;]</value>
      <webElementGuid>8ac6b08f-b886-4bad-a2a0-25d0a21cbf6c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='userDetails']/div[2]/label</value>
      <webElementGuid>1768cbf6-1139-4236-9cf1-e823783cf210</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tanya Pratama'])[1]/following::label[1]</value>
      <webElementGuid>7d771acf-b86f-4ae9-b157-c4194e6b0eda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ORDER PAYMENT'])[2]/following::label[4]</value>
      <webElementGuid>31039cab-10e8-4234-9e14-29db78f3d53a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Brisbane'])[1]/preceding::label[1]</value>
      <webElementGuid>b01f46d0-be9c-475e-9f9a-b5990a8137fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Australia'])[1]/preceding::label[2]</value>
      <webElementGuid>1a605440-009d-4aff-9b3d-abc980d2716a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='hdfhagkerf']/parent::*</value>
      <webElementGuid>122d93d1-8407-47bf-ad25-2ae6335d1400</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/label</value>
      <webElementGuid>9416a297-91c3-48e7-aaa6-a8ecddb0487b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'hdfhagkerf' or . = 'hdfhagkerf')]</value>
      <webElementGuid>19817223-1eb1-46d1-a2e1-e563c44f4dab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
