<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_PAY NOW</name>
   <tag></tag>
   <elementGuidId>7bcb9e13-f608-4e13-a15d-15b8a5fdc3db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='pay_now_btn_SAFEPAY']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#pay_now_btn_SAFEPAY</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#pay_now_btn_SAFEPAY</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ffb47424-f2d3-452e-96d9-276c304e5e68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pay_now_btn_SAFEPAY</value>
      <webElementGuid>627c17ff-3a08-41ba-bf62-492f35c8bcd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>71f01aa8-f7af-4bff-83c3-30040a7638f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sec-sender-a ng-scope</value>
      <webElementGuid>d4c46bb5-735f-4708-807a-708ad764b41a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5c7406cd-a64c-4e4e-8635-27f82ceeeb07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-click</name>
      <type>Main</type>
      <value>senderCtrl.send()</value>
      <webElementGuid>e5edad21-9285-4d0d-8fb3-0e3e09566bec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PAY NOW</value>
      <webElementGuid>a6388051-68ec-4a4f-989c-2c21f0d6fe52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pay_now_btn_SAFEPAY&quot;)</value>
      <webElementGuid>2edb85fa-89f7-469e-8374-bc5413f8d2e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='pay_now_btn_SAFEPAY']</value>
      <webElementGuid>93bb3343-a59a-48c1-9b19-7ee81dcf039b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//sec-sender[@id='payNowSPDrtv']/button</value>
      <webElementGuid>ef5bd7dd-cf19-4900-a056-ff2890999287</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back to shipping details'])[1]/following::button[1]</value>
      <webElementGuid>1ba33526-08ea-49c6-9d4b-81210a60027e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save changes in profile for future use'])[2]/following::button[1]</value>
      <webElementGuid>d2645fd2-5c42-4e76-97c9-63e6c3cd261a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MasterCredit'])[1]/preceding::button[1]</value>
      <webElementGuid>c3d0b140-02f7-40fc-b0ca-710293cc6736</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit'])[1]/preceding::button[1]</value>
      <webElementGuid>7275ad4a-4f94-430d-8c30-fce122610fe8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='PAY NOW']/parent::*</value>
      <webElementGuid>4ee57ac7-9c17-4530-8bf9-84e74985c24d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/sec-sender/button</value>
      <webElementGuid>9fe783e3-ed43-47e2-96a1-bf868db5edb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'pay_now_btn_SAFEPAY' and @type = 'button' and (text() = 'PAY NOW' or . = 'PAY NOW')]</value>
      <webElementGuid>23c3161d-ffad-4415-901e-96c8491f5bda</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
