<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_NEXT</name>
   <tag></tag>
   <elementGuidId>31b5c115-e92b-47ba-83bb-f81e2e9cb7ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='next_btn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#next_btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;NEXT&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>361a5873-38c3-4c7d-aa88-8b212b170028</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>next_btn</value>
      <webElementGuid>1268c503-9588-4ab5-985c-0166e2ec0459</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4b51d20b-0a6c-4082-b124-e1acfd564ec0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-click</name>
      <type>Main</type>
      <value>shippingDetails_next()</value>
      <webElementGuid>97f9e930-e7f6-47ca-b5d9-75dcb7e90590</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-button nextBtn marginTop75 ng-scope</value>
      <webElementGuid>e0811d94-bbf9-4b10-9ab0-fe49aa6351a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>translate</name>
      <type>Main</type>
      <value>NEXT</value>
      <webElementGuid>5c6a2af6-033f-4cae-8ce2-a2f90355bec2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NEXT</value>
      <webElementGuid>79d41703-672c-42ef-abb3-b66a2a9f7e04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;userSection&quot;)/div[1]/div[@class=&quot;mobileBtnHandler&quot;]/button[@id=&quot;next_btn&quot;]</value>
      <webElementGuid>b69e4f66-0727-49ce-baae-1ec41ffd0f80</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='next_btn']</value>
      <webElementGuid>af0dda68-e08e-4a88-b583-3d36c9ddb413</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='userSection']/div/div[3]/button</value>
      <webElementGuid>29796e0f-69bb-4f6a-aef2-dffe2baa27b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SHIPPING BY:'])[1]/following::button[1]</value>
      <webElementGuid>adbd8236-01df-45ab-bf41-fb302527d518</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit shipping details'])[1]/following::button[1]</value>
      <webElementGuid>895756b2-20c0-4066-8a47-2ab1568bf787</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recipient details'])[1]/preceding::button[1]</value>
      <webElementGuid>7cf85798-022f-4918-b968-5b471bd0d3d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='First Name'])[2]/preceding::button[1]</value>
      <webElementGuid>e7c6fb89-59b6-4e64-a83b-92f02f5c2052</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='NEXT']/parent::*</value>
      <webElementGuid>4ade01e8-3b62-477f-879a-0e499070e152</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button</value>
      <webElementGuid>bf7c936d-121d-487e-8989-99f751f1811f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'next_btn' and (text() = 'NEXT' or . = 'NEXT')]</value>
      <webElementGuid>8f07a130-ccc9-44cc-94d5-57aad5d1f439</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
