<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_REGISTRATION</name>
   <tag></tag>
   <elementGuidId>190152eb-54c4-4d19-8375-58155968d122</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='registration_btn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#registration_btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;REGISTRATION&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8de2fcb6-1f80-454c-bab7-3c34dd471504</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>registration_btn</value>
      <webElementGuid>3bfcb09a-2327-4bf7-88d5-e6b8870a086c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>74e51775-1d0c-47a5-bc9b-7cfb79bbf26b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sec-sender-a ng-scope</value>
      <webElementGuid>10dbe002-917c-4355-aa35-576a31fd6b87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>cc81537e-f978-4c5d-a740-6a5470bbd229</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-click</name>
      <type>Main</type>
      <value>senderCtrl.send()</value>
      <webElementGuid>b1a11d50-05fa-4033-87aa-f198402d63e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>REGISTRATION</value>
      <webElementGuid>4154bf10-7449-49ed-9802-d27890a4e74f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;registration_btn&quot;)</value>
      <webElementGuid>5497b875-ea97-49e5-a8d2-797ecd5bfe9d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='registration_btn']</value>
      <webElementGuid>3739eec3-19ad-44a9-ab10-c5a0d685b02d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='newClient']/div/sec-form/sec-sender/button</value>
      <webElementGuid>484bdcd6-b21d-47d7-a464-ce968ed5d96f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New user?'])[1]/following::button[1]</value>
      <webElementGuid>571ba8ea-efcf-4bb0-bd62-8bb20e80345c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LOGIN'])[1]/following::button[1]</value>
      <webElementGuid>3117dc68-433e-46d5-93ed-1d46f0d6ccce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ORDER SUMMARY'])[1]/preceding::button[1]</value>
      <webElementGuid>a90b3c7f-fcdb-4eff-add7-f324f1517afc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PRODUCT'])[1]/preceding::button[1]</value>
      <webElementGuid>fd834356-648f-4fd5-b4e3-140cffa67fc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='REGISTRATION']/parent::*</value>
      <webElementGuid>51c92f78-6701-449f-ba96-5c69740a056e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/sec-form/sec-sender/button</value>
      <webElementGuid>ab57f2d9-1156-4b0f-8d15-755b20b68281</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'registration_btn' and @type = 'button' and (text() = 'REGISTRATION' or . = 'REGISTRATION')]</value>
      <webElementGuid>1554c1fd-5eb6-4e9b-a63b-481c34a737bd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
